export {documentTable,statusEnum,documentRelations} from './document'
export {educationTable,educationRelations} from './education'
export {experienceTable,experienceRelations} from './experience'
export {personalInfoTable,personalInfoRelations} from './personal-info'
export {skillsTable,skillsRelations} from './skills'
export {projectTable,projectRelations} from './project'